import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { admin } from "better-auth/plugins/admin";
import { twoFactor } from "better-auth/plugins/two-factor";
import { CLIENT_IP_HEADER } from "@/server/client-ip.server";
import { getDb, type Database } from "@/server/db/index.server";
import {
  adminAccounts,
  adminRateLimits,
  adminSessions,
  adminTwoFactors,
  adminUsers,
  adminVerifications,
} from "@/server/db/schema";
import { appUrl, getEnv } from "@/server/env.server";
import { recordAudit } from "@/server/audit.server";
import { logger } from "@/server/logger.server";
import { mailLayout } from "@/server/mail.server";
import { deliverAccountMail } from "./auth-mail.server";
import { PASSWORD_LIMITS } from "@/features/auth/domain/password-rules";
import { hashPassword, verifyPassword } from "./password.server";
import { ac, roles } from "./permissions.server";
import { AUTH_RATE_LIMIT_RULES, authHooks, FRESH_SESSION_SECONDS } from "./auth-shared.server";

export const ADMIN_AUTH_BASE_PATH = "/api/admin/auth";

/**
 * The `admin` plugin gives Better Auth the account role and blocking. Its HTTP
 * routes (create, change role, change another admin's e-mail or password…) stay
 * closed: they do not require 2FA or a fresh session and do not write audit logs.
 * The panel performs these operations through its own actions.
 */
const adminPlugin = admin({
  ac,
  roles,
  defaultRole: "viewer",
  adminRoles: ["owner"],
  allowImpersonatingAdmins: false,
  bannedUserMessage: "Esta conta está desativada. Fale com o dono do painel.",
});

const DISABLED_ADMIN_PLUGIN_PATHS = Object.values(adminPlugin.endpoints).map(
  (endpoint) => endpoint.path,
);

function createAdminAuth(db: Database, secret: string) {
  const production = process.env.NODE_ENV === "production";

  return betterAuth({
    appName: "Nelcota Admin",
    baseURL: appUrl(),
    basePath: ADMIN_AUTH_BASE_PATH,
    secret,
    trustedOrigins: [appUrl()],
    telemetry: { enabled: false },
    disabledPaths: DISABLED_ADMIN_PLUGIN_PATHS,
    database: drizzleAdapter(db, {
      provider: "pg",
      schema: {
        adminUsers,
        adminSessions,
        adminAccounts,
        adminVerifications,
        adminTwoFactors,
        adminRateLimits,
      },
    }),
    user: { modelName: "adminUsers" },
    account: { modelName: "adminAccounts", accountLinking: { enabled: false } },
    verification: { modelName: "adminVerifications" },
    session: {
      modelName: "adminSessions",
      // 12 h without use kill the session; the absolute maximum (7 days) is checked in the DAL.
      expiresIn: 12 * 60 * 60,
      updateAge: 60 * 60,
      // Critical actions require a sign-in in the last 10 min (password, role, 2FA, deletion).
      freshAge: FRESH_SESSION_SECONDS,
      // No cookie cache: a revoked session stops working on the next request.
      cookieCache: { enabled: false },
    },
    emailAndPassword: {
      enabled: true,
      // Admins only join by invitation.
      disableSignUp: true,
      minPasswordLength: PASSWORD_LIMITS.admin.min,
      maxPasswordLength: PASSWORD_LIMITS.admin.max,
      password: { hash: hashPassword, verify: verifyPassword },
      resetPasswordTokenExpiresIn: 30 * 60,
      revokeSessionsOnPasswordReset: true,
      onPasswordReset: async ({ user }) => {
        await recordAudit(
          db,
          { adminId: user.id },
          { action: "auth.password_reset", resourceType: "admin_user", resourceId: user.id },
        ).catch((error: unknown) => logger.error({ err: error }, "failed to audit password"));
      },
      // Fired without waiting: the response time does not reveal whether the e-mail exists.
      sendResetPassword: async ({ user, url }) => {
        const mail = mailLayout({
          title: "Redefinir senha do painel Nelcota",
          intro: `Olá, ${user.name}. Recebemos um pedido para redefinir a senha do painel. Use o botão abaixo para escolher uma nova senha.`,
          notice: "Link válido por 30 minutos · Uso único",
          action: { label: "Definir nova senha", url },
          outro: "Se não foi você, ignore este e-mail: sua senha continua a mesma.",
        });
        await deliverAccountMail({ to: user.email, subject: "Redefinir senha do painel", ...mail });
      },
    },
    rateLimit: {
      enabled: true,
      storage: "database",
      modelName: "adminRateLimits",
      window: 60,
      max: 100,
      customRules: AUTH_RATE_LIMIT_RULES,
    },
    advanced: {
      cookiePrefix: "nelcota-admin",
      useSecureCookies: production,
      defaultCookieAttributes: { sameSite: "strict", httpOnly: true, path: "/" },
      // IDs generated by Postgres (uuidv7()).
      database: { generateId: false },
      ipAddress: { ipAddressHeaders: [CLIENT_IP_HEADER] },
    },
    hooks: authHooks(db, secret, "admin", { audit: true }),
    databaseHooks: {
      user: {
        update: {
          // 2FA on/off (the plugin writes twoFactorEnabled on the user).
          after: async (user, context) => {
            if (!context?.path.startsWith("/two-factor/")) return;
            if (!("twoFactorEnabled" in user)) return;
            await recordAudit(
              db,
              { adminId: user.id },
              {
                action: user.twoFactorEnabled
                  ? "auth.two_factor_enabled"
                  : "auth.two_factor_disabled",
                resourceType: "admin_user",
                resourceId: user.id,
              },
            ).catch((error: unknown) => logger.error({ err: error }, "failed to audit 2FA"));
          },
        },
      },
      account: {
        update: {
          // Password changed in the account. A reset is audited in onPasswordReset: it goes
          // through updateMany, so this hook receives a row count instead of the account.
          after: async (account, context) => {
            if (!context?.path || !/password/.test(context.path)) return;
            if (context.path.includes("reset")) return;
            await recordAudit(
              db,
              { adminId: account.userId },
              {
                action: "auth.password_changed",
                resourceType: "admin_user",
                resourceId: account.userId,
              },
            ).catch((error: unknown) => logger.error({ err: error }, "failed to audit password"));
          },
        },
      },
    },
    plugins: [
      twoFactor({
        issuer: "Nelcota Admin",
        schema: { twoFactor: { modelName: "adminTwoFactors" } },
        backupCodeOptions: { amount: 10, length: 10 },
      }),
      adminPlugin,
    ],
  });
}

export type AdminAuth = ReturnType<typeof createAdminAuth>;

let instance: AdminAuth | undefined;

/** Admin Better Auth instance, or `undefined` without a database or ADMIN_AUTH_SECRET. */
export function getAdminAuth(): AdminAuth | undefined {
  if (instance) return instance;
  const db = getDb();
  const secret = getEnv().ADMIN_AUTH_SECRET;
  if (!secret) return undefined;
  instance = createAdminAuth(db, secret);
  return instance;
}

/** Tests only: instance with explicit database and secret. */
export function createAdminAuthForTests(db: Database, secret: string): AdminAuth {
  return createAdminAuth(db, secret);
}
