import { index, layout, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("conta", "routes/account.tsx"),
  route("privacidade", "routes/privacy.tsx"),
  route("novidades", "routes/changelog.tsx"),
  route("sala/:codigo", "routes/room.tsx", { id: "room" }),
  layout("routes/access/layout.tsx", [
    route("entrar", "routes/access/sign-in.tsx"),
    route("entrar/2fa", "routes/access/two-factor.tsx"),
    route("cadastro", "routes/access/sign-up.tsx"),
    route("verificar-email", "routes/access/verify-email.tsx"),
    route("recuperar-senha", "routes/access/forgot-password.tsx"),
    route("redefinir-senha", "routes/access/reset-password.tsx"),
  ]),
  layout("routes/admin/access/layout.tsx", [
    route("admin/entrar", "routes/admin/access/sign-in.tsx"),
    route("admin/recuperar-senha", "routes/admin/access/forgot-password.tsx"),
    route("admin/redefinir-senha", "routes/admin/access/reset-password.tsx"),
    route("admin/verificar-2fa", "routes/admin/access/two-factor.tsx"),
    route("admin/convite/:token", "routes/admin/access/invitation.tsx"),
  ]),
  layout("routes/admin/panel/layout.tsx", [
    route("admin", "routes/admin/panel/dashboard.tsx"),
    route("admin/usuarios", "routes/admin/panel/participants.tsx"),
    route("admin/usuarios/:id", "routes/admin/panel/participant-detail.tsx"),
    route("admin/salas", "routes/admin/panel/rooms.tsx"),
    route("admin/salas/:id", "routes/admin/panel/room-detail.tsx"),
    route("admin/compartilhamentos", "routes/admin/panel/shares.tsx"),
    route("admin/auditoria", "routes/admin/panel/audit.tsx"),
    route("admin/configuracoes", "routes/admin/panel/settings.tsx"),
    route("admin/conta/seguranca", "routes/admin/panel/security.tsx"),
    route("admin/conta/sessoes", "routes/admin/panel/sessions.tsx"),
    route("admin/sem-permissao", "routes/admin/panel/no-permission.tsx"),
  ]),
  route("api/auth/*", "routes/api/auth.ts"),
  route("api/admin/auth/*", "routes/api/admin/auth.ts"),
  route("api/token", "routes/api/room/token.ts"),
  route("api/sala/mao", "routes/api/room/hand.ts"),
  route("api/livekit/webhook", "routes/api/room/livekit-webhook.ts"),
  route("api/health", "routes/api/health.ts"),
  route("api/ready", "routes/api/ready.ts"),
  route("api/conta/dados", "routes/api/account/data.ts"),
  route("api/admin/exportar/usuarios", "routes/api/admin/export-participants.ts"),
  route("api/admin/exportar/salas", "routes/api/admin/export-rooms.ts"),
  route("api/admin/exportar/compartilhamentos", "routes/api/admin/export-shares.ts"),
  route("api/admin/exportar/auditoria", "routes/api/admin/export-audit.ts"),
  route("api/operations/:operation", "routes/api/operations.ts"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
